name: DeepLeague2
channels:
- menpo
- defaults
dependencies:
- certifi=2016.2.28=py36_0
- openssl=1.0.2l=0
- pip=9.0.1=py36_1
- python=3.6.2=0
- readline=6.2=2
- setuptools=36.4.0=py36_1
- sqlite=3.13.0=0
- tk=8.5.18=0
- wheel=0.29.0=py36_0
- xz=5.2.3=0
- zlib=1.2.11=0
- ffmpeg=3.1.3=0
- pip:
  - bleach==1.5.0
  - cycler==0.10.0
  - enum34==1.1.6
  - h5py==2.7.1
  - html5lib==0.9999999
  - keras==2.1.3
  - markdown==2.6.11
  - matplotlib==2.1.2
  - numpy==1.14.0
  - opencv-python==3.4.0.12
  - pillow==5.0.0
  - protobuf==3.5.1
  - pyparsing==2.2.0
  - python-dateutil==2.6.1
  - pytz==2017.3
  - pyyaml==3.12
  - scipy==1.0.0
  - six==1.11.0
  - tensorflow==1.4.1
  - tensorflow-tensorboard==0.4.0
  - werkzeug==0.14.1
  - youtube-dl==2018.1.21
